### ISSUE TITLE
ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 401 | Attempted to reach: 

### ISSUE THREAD

**Issue by wsdo** [Azure-Samples/ms-identity-javascript-nodejs-tutorial#43] opened 2022-09-28 02:46 UTC
ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 401 | Attempted to reach: 

# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ]   3) Deploy to Azure Storage and App Service
    - [ ] 4-1) Use App Roles for Role-based Access Control
    - [ ] 4-2) Use Security Groups for Role-based Access Control
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment] 2022-09-28 16:33
@wsdo unfortunately, due to a bug in msal-node, the errors from the server are obfuscated by this generic network error, so it's not clear what the root cause here. A fix for this is coming along, which you can track [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5175). 

In the meantime, I could be able to guess the actual cause if you could provide more details (your app scenario, app configuration parameters etc.) Apologies for the confusion.

**Closed** 2022-10-21 00:25 UTC
Labels: no-issue-activity
